var quotes = ["I think that God, in creating man, somewhat overestimated his ability.",
"The world is a stage, but the play is badly cast.",
"Always forgive your enemies; nothing annoys them so much.",
"It is absurd to divide people into good and bad. People are either charming or tedious.",
"The only thing to do with good advice is pass it on. It is never any use to oneself.",
"Some cause happiness wherever they go; others whenever they go.",
"What is a cynic? A man who knows the price of everything and the value of nothing.",
"A little sincerity is a dangerous thing, and a great deal of it is absolutely fatal.",
"When I was young I thought that money was the most important thing in life; now that I am old I know that it is.",
"There are only two tragedies in life: one is not getting what one wants, and the other is getting it.",
"Work is the curse of the drinking classes.",
"Anyone who lives within their means suffers from a lack of imagination.",
"True friends stab you in the front.",
"All women become like their mothers. That is their tragedy. No man does. That's his.",
"Fashion is a form of ugliness so intolerable that we have to alter it every six months.",
"There is only one thing in life worse than being talked about, and that is not being talked about.",
"Genius is born—not paid.",
"Morality is simply the attitude we adopt towards people whom we personally dislike.",
"How can a woman be expected to be happy with a man who insists on treating her as if she were a perfectly normal human being?",
"A gentleman is one who never hurts anyone’s feelings unintentionally.",
"My own business always bores me to death; I prefer other people’s.",
"The old believe everything, the middle-aged suspect everything, the young know everything.",
"I like men who have a future and women who have a past.",
"There are two ways of disliking poetry; one way is to dislike it, the other is to read Pope.",
"Quotation is a serviceable substitute for wit."]

module.exports = quotes;